"""Execution algorithms for optimal order slicing and scheduling.

Implements standard institutional execution strategies:
  - **TWAP**: Time-weighted average price — uniform slicing over time.
  - **VWAP**: Volume-weighted average price — slicing proportional to
    expected intraday volume profile.
  - **Implementation Shortfall**: Almgren-Chriss optimal trajectory
    minimizing E[cost] + lambda * Var[cost].
  - **Participation (POV)**: Trade as fixed % of market volume.

Each algorithm takes a parent order and produces a schedule of child
slices with timing and quantities.

Usage::

    order = ParentOrder("AAPL", "BUY", 10000, start, end)
    algo = TWAPAlgo(order, n_slices=20)
    schedule = algo.generate_schedule()
    report = algo.simulate(mid_prices)  # backtest execution quality

References:
  - Almgren & Chriss (2001), "Optimal Execution of Portfolio Transactions"
  - Berkowitz et al. (1988), "Total Cost of Transactions on the NYSE"
"""

import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from typing import Optional

import numpy as np

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------


@dataclass
class ParentOrder:
    """Top-level order to be executed by an algorithm."""

    ticker: str
    side: str  # "BUY" or "SELL"
    total_qty: int
    start_time: datetime
    end_time: datetime
    urgency: float = 0.5  # 0=passive, 1=aggressive

    @property
    def duration_seconds(self) -> float:
        return (self.end_time - self.start_time).total_seconds()

    @property
    def n_minutes(self) -> int:
        return max(1, int(self.duration_seconds / 60))


@dataclass
class ChildSlice:
    """Single child order slice generated by the algorithm."""

    slice_id: int
    target_time: datetime
    target_qty: int
    is_final: bool = False


@dataclass
class SliceResult:
    """Execution result for one child slice."""

    slice_id: int
    target_qty: int
    filled_qty: int
    avg_fill_price: float
    arrival_price: float
    slippage_bps: float


@dataclass
class ExecutionReport:
    """Final report for a completed parent order execution."""

    parent_order: ParentOrder
    algo_name: str
    slices: list[SliceResult]

    @property
    def total_filled(self) -> int:
        return sum(s.filled_qty for s in self.slices)

    @property
    def fill_rate(self) -> float:
        return self.total_filled / max(self.parent_order.total_qty, 1)

    @property
    def avg_fill_price(self) -> float:
        total_value = sum(s.filled_qty * s.avg_fill_price for s in self.slices)
        total_qty = self.total_filled
        return total_value / max(total_qty, 1)

    @property
    def arrival_price(self) -> float:
        return self.slices[0].arrival_price if self.slices else 0.0

    @property
    def is_bps(self) -> float:
        """Implementation shortfall vs arrival price (in bps)."""
        if self.arrival_price == 0:
            return 0.0
        raw = (self.avg_fill_price - self.arrival_price) / self.arrival_price * 10_000
        return raw if self.parent_order.side == "BUY" else -raw

    @property
    def mean_slippage_bps(self) -> float:
        if not self.slices:
            return 0.0
        return float(np.mean([s.slippage_bps for s in self.slices]))

    def summary(self) -> str:
        return (
            f"{self.algo_name}: {self.total_filled}/{self.parent_order.total_qty} "
            f"filled ({self.fill_rate:.0%}), "
            f"IS={self.is_bps:.1f}bps, "
            f"avg_slip={self.mean_slippage_bps:.1f}bps"
        )


@dataclass
class VolumeProfile:
    """Intraday volume distribution for VWAP algo."""

    bucket_minutes: int
    fractions: list[float]  # sum = 1.0

    @classmethod
    def uniform(cls, trading_minutes: int = 390, bucket_minutes: int = 5) -> "VolumeProfile":
        n = max(1, trading_minutes // bucket_minutes)
        return cls(bucket_minutes=bucket_minutes, fractions=[1.0 / n] * n)

    @classmethod
    def u_shaped(cls, trading_minutes: int = 390, bucket_minutes: int = 5) -> "VolumeProfile":
        """Typical US equity U-shape: high at open/close, low midday."""
        n = max(1, trading_minutes // bucket_minutes)
        x = np.linspace(0, 1, n)
        raw = 0.7 + 0.8 * (4 * (x - 0.5) ** 2)
        fracs = (raw / raw.sum()).tolist()
        return cls(bucket_minutes=bucket_minutes, fractions=fracs)


# ---------------------------------------------------------------------------
# Abstract base
# ---------------------------------------------------------------------------


class ExecutionAlgo(ABC):
    """Abstract base class for execution algorithms."""

    def __init__(self, parent_order: ParentOrder):
        self.parent_order = parent_order

    @property
    @abstractmethod
    def name(self) -> str:
        ...

    @abstractmethod
    def generate_schedule(self) -> list[ChildSlice]:
        ...

    def simulate(
        self,
        mid_prices: np.ndarray,
        spread_bps: float = 5.0,
        impact_bps_per_lot: float = 0.1,
    ) -> ExecutionReport:
        """Simulate execution against a mid-price path.

        Parameters
        ----------
        mid_prices : np.ndarray
            One mid price per slice in the schedule.
        spread_bps : float
            Half-spread in basis points.
        impact_bps_per_lot : float
            Linear market impact per 100 shares.

        Returns
        -------
        ExecutionReport
        """
        schedule = self.generate_schedule()
        results = []

        for i, child in enumerate(schedule):
            price_idx = min(i, len(mid_prices) - 1)
            mid = mid_prices[price_idx]

            # Half-spread cost
            spread_cost = mid * spread_bps / 10_000
            # Market impact (linear in qty)
            impact = mid * impact_bps_per_lot / 10_000 * (child.target_qty / 100)

            sign = 1 if self.parent_order.side == "BUY" else -1
            fill_price = mid + sign * (spread_cost + impact)

            slippage = (fill_price - mid) / mid * 10_000
            if self.parent_order.side == "SELL":
                slippage = -slippage

            results.append(SliceResult(
                slice_id=child.slice_id,
                target_qty=child.target_qty,
                filled_qty=child.target_qty,
                avg_fill_price=fill_price,
                arrival_price=mid_prices[0],
                slippage_bps=slippage,
            ))

        return ExecutionReport(
            parent_order=self.parent_order,
            algo_name=self.name,
            slices=results,
        )


# ---------------------------------------------------------------------------
# TWAP
# ---------------------------------------------------------------------------


class TWAPAlgo(ExecutionAlgo):
    """Time-weighted average price: uniform slicing over time.

    Parameters
    ----------
    parent_order : ParentOrder
    n_slices : int, optional
        Number of slices. Default: one per minute of duration.
    randomize_pct : float
        Random jitter on slice qty to reduce predictability.
    """

    def __init__(
        self,
        parent_order: ParentOrder,
        n_slices: int | None = None,
        randomize_pct: float = 0.0,
        seed: int | None = None,
    ):
        super().__init__(parent_order)
        self.n_slices = n_slices or max(1, parent_order.n_minutes)
        self.randomize_pct = randomize_pct
        self._rng = np.random.default_rng(seed)

    @property
    def name(self) -> str:
        return "TWAP"

    def generate_schedule(self) -> list[ChildSlice]:
        po = self.parent_order
        n = self.n_slices
        base_qty = po.total_qty // n
        remainder = po.total_qty % n
        interval = timedelta(seconds=po.duration_seconds / n)

        schedule = []
        remaining = po.total_qty

        for i in range(n):
            qty = base_qty + (1 if i < remainder else 0)

            if self.randomize_pct > 0 and i < n - 1:
                jitter = self._rng.uniform(-self.randomize_pct, self.randomize_pct)
                qty = max(1, int(qty * (1 + jitter)))
                qty = min(qty, remaining)

            if i == n - 1:
                qty = remaining

            remaining -= qty
            schedule.append(ChildSlice(
                slice_id=i,
                target_time=po.start_time + i * interval,
                target_qty=qty,
                is_final=(i == n - 1),
            ))

        return schedule


# ---------------------------------------------------------------------------
# VWAP
# ---------------------------------------------------------------------------


class VWAPAlgo(ExecutionAlgo):
    """Volume-weighted average price: slice proportional to volume profile.

    Parameters
    ----------
    parent_order : ParentOrder
    volume_profile : VolumeProfile, optional
        Expected intraday volume curve. Default: U-shaped.
    min_slice_qty : int
        Minimum shares per slice.
    """

    def __init__(
        self,
        parent_order: ParentOrder,
        volume_profile: VolumeProfile | None = None,
        min_slice_qty: int = 1,
    ):
        super().__init__(parent_order)
        self.volume_profile = volume_profile or VolumeProfile.u_shaped()
        self.min_slice_qty = min_slice_qty

    @property
    def name(self) -> str:
        return "VWAP"

    def generate_schedule(self) -> list[ChildSlice]:
        po = self.parent_order
        fracs = self.volume_profile.fractions
        n_buckets = len(fracs)

        # Map parent order window onto volume profile buckets
        order_minutes = po.n_minutes
        profile_minutes = n_buckets * self.volume_profile.bucket_minutes

        # Scale: use fraction of the profile that covers the order window
        start_bucket = 0
        end_bucket = min(n_buckets, max(1, order_minutes // self.volume_profile.bucket_minutes))

        sub_fracs = fracs[start_bucket:end_bucket]
        if not sub_fracs:
            sub_fracs = [1.0]

        # Renormalize
        total_frac = sum(sub_fracs)
        if total_frac > 0:
            sub_fracs = [f / total_frac for f in sub_fracs]

        interval = timedelta(minutes=self.volume_profile.bucket_minutes)
        schedule = []
        remaining = po.total_qty

        for i, frac in enumerate(sub_fracs):
            if i == len(sub_fracs) - 1:
                qty = remaining
            else:
                qty = max(self.min_slice_qty, round(po.total_qty * frac))
                qty = min(qty, remaining)

            remaining -= qty
            if qty > 0:
                schedule.append(ChildSlice(
                    slice_id=i,
                    target_time=po.start_time + i * interval,
                    target_qty=qty,
                    is_final=(i == len(sub_fracs) - 1),
                ))

        return schedule


# ---------------------------------------------------------------------------
# Implementation Shortfall (Almgren-Chriss)
# ---------------------------------------------------------------------------


class ISAlgo(ExecutionAlgo):
    """Almgren-Chriss optimal execution trajectory.

    Minimizes E[cost] + lambda * Var[cost] to produce an exponential
    trading schedule. High urgency front-loads, low urgency is TWAP-like.

    Parameters
    ----------
    parent_order : ParentOrder
    volatility : float
        Daily volatility of the asset (e.g. 0.02 = 2%).
    eta : float
        Temporary impact coefficient.
    n_steps : int, optional
    """

    def __init__(
        self,
        parent_order: ParentOrder,
        volatility: float = 0.02,
        eta: float = 1e-4,
        n_steps: int | None = None,
    ):
        super().__init__(parent_order)
        self.volatility = volatility
        self.eta = eta
        self.n_steps = n_steps or min(max(1, parent_order.n_minutes), 50)

    @property
    def name(self) -> str:
        return "IS_AlmgrenChriss"

    def _optimal_trajectory(self) -> np.ndarray:
        """Compute Almgren-Chriss optimal execution trajectory.

        Returns array of shares to trade in each interval.
        """
        po = self.parent_order
        T = po.duration_seconds / (6.5 * 3600)  # fraction of trading day
        X = po.total_qty
        sigma = self.volatility

        # Map urgency [0,1] to risk aversion on log scale
        lam = 10 ** (-8 + 4 * po.urgency)

        kappa = np.sqrt(lam * sigma**2 / max(self.eta, 1e-10))
        tau = np.linspace(0, T, self.n_steps + 1)

        kT = kappa * T
        if kT < 1e-10:
            # Low risk aversion → uniform
            holdings = X * (1 - tau / max(T, 1e-10))
        else:
            holdings = X * np.sinh(kappa * (T - tau)) / np.sinh(kT)

        trades = np.diff(-holdings)
        trades = np.maximum(trades, 0)

        if trades.sum() > 0:
            trades = trades / trades.sum() * X

        return trades

    def generate_schedule(self) -> list[ChildSlice]:
        po = self.parent_order
        trajectory = self._optimal_trajectory()
        interval = timedelta(seconds=po.duration_seconds / self.n_steps)

        schedule = []
        remaining = po.total_qty

        for i, trade_qty in enumerate(trajectory):
            if i == len(trajectory) - 1:
                qty = remaining
            else:
                qty = max(0, round(trade_qty))
                qty = min(qty, remaining)

            remaining -= qty
            if qty > 0:
                schedule.append(ChildSlice(
                    slice_id=len(schedule),
                    target_time=po.start_time + i * interval,
                    target_qty=qty,
                    is_final=(i == len(trajectory) - 1),
                ))

        return schedule


# ---------------------------------------------------------------------------
# Participation (POV)
# ---------------------------------------------------------------------------


class ParticipationAlgo(ExecutionAlgo):
    """Trade as a fixed percentage of market volume.

    Parameters
    ----------
    parent_order : ParentOrder
    target_rate : float
        Target participation as fraction of volume (e.g. 0.10 = 10%).
    expected_adv : int
        Expected average daily volume for scheduling.
    check_interval_minutes : int
        How often to place slices.
    """

    def __init__(
        self,
        parent_order: ParentOrder,
        target_rate: float = 0.10,
        expected_adv: int = 1_000_000,
        check_interval_minutes: int = 5,
    ):
        super().__init__(parent_order)
        self.target_rate = target_rate
        self.expected_adv = expected_adv
        self.check_interval_minutes = check_interval_minutes

    @property
    def name(self) -> str:
        return "POV"

    def generate_schedule(self) -> list[ChildSlice]:
        po = self.parent_order
        interval = timedelta(minutes=self.check_interval_minutes)
        trading_day_minutes = 390

        # Expected volume per interval
        vol_per_interval = (
            self.expected_adv
            * self.check_interval_minutes
            / trading_day_minutes
        )
        target_qty_per_interval = int(vol_per_interval * self.target_rate)
        target_qty_per_interval = max(1, target_qty_per_interval)

        n_intervals = max(1, int(po.duration_seconds / 60 / self.check_interval_minutes))

        schedule = []
        remaining = po.total_qty

        for i in range(n_intervals):
            qty = min(target_qty_per_interval, remaining)
            if qty <= 0:
                break

            remaining -= qty
            schedule.append(ChildSlice(
                slice_id=i,
                target_time=po.start_time + i * interval,
                target_qty=qty,
                is_final=(remaining == 0),
            ))

            if remaining == 0:
                break

        # If remaining, add final slice
        if remaining > 0:
            schedule.append(ChildSlice(
                slice_id=len(schedule),
                target_time=po.end_time,
                target_qty=remaining,
                is_final=True,
            ))

        return schedule


# ---------------------------------------------------------------------------
# Factory
# ---------------------------------------------------------------------------


def create_algo(algo_name: str, parent_order: ParentOrder, **kwargs) -> ExecutionAlgo:
    """Factory for creating execution algorithms.

    Parameters
    ----------
    algo_name : str
        One of: "TWAP", "VWAP", "IS", "POV"
    parent_order : ParentOrder
    **kwargs : Algorithm-specific parameters.
    """
    algos = {
        "TWAP": TWAPAlgo,
        "VWAP": VWAPAlgo,
        "IS": ISAlgo,
        "POV": ParticipationAlgo,
    }
    key = algo_name.upper()
    if key not in algos:
        raise ValueError(f"Unknown algo: {algo_name}. Choose from {list(algos.keys())}")
    return algos[key](parent_order, **kwargs)
